jobs:
- job: macOS
  pool:
    vmImage: macOS-10.14
  steps:
    - bash: |
        set -e
        sudo xcode-select --switch /Applications/Xcode_10.2.app/Contents/Developer
        brew update
        HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/zengxs/homebrew-mine"
        mkdir -p "$HOMEBREW_TAP_DIR"
        rm -rf "$HOMEBREW_TAP_DIR"
        ln -s "$PWD" "$HOMEBREW_TAP_DIR"
        cd "$HOMEBREW_TAP_DIR"
      displayName: Update homebrew

    - bash: brew test-bot
      displayName: Run brew test-bot

    - bash: brew cask ci
      displayName: Run brew cask ci
